name: TestDockerBuild

on:
    schedule:
        - cron: '30 1,13 * * *'
    push:
        branches:
            - master
        paths:
            - 'Dockerfile'
    pull_request:
        branches:
            - master
        paths:
            - 'Dockerfile'

jobs:
  docker_build:
    name: test docker build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          with:
              driver: docker
        - name: build
          uses: docker/build-push-action@v2
          with:
              push: false
              tags: detic_ros:latest
